### ISSUE TITLE
Easier Windows setup?

### ISSUE THREAD

**Issue by JohnDMcMaster** [AdamLaurie/rompar#17]
Its possible to run on Windows, but requires knowing about things like pip. It sounds like there are some options to create simple MSI installers. Maybe we can get a volunteer to work on this? @diamondman might be able to provide some direction, but not sure if he has time he can devote right now

"Either use the NSIS tool (https://nsis.sourceforge.io/Main_Page) or MS has some tools for generating MSIs from a set of files and registry keys"

**Comment by diamondman** [comment]
There are several installers I am looking at, all happen to be briefly described here: https://wiki.wxwidgets.org/Installers

WiX can make msi files which are more trustworthy than exe installers, but I read it is overly complicated.
NSIS is easy from my experience.
I hear inno setup is even easier.

**Comment by diamondman** [comment]
https://jrsoftware.org/isinfo.php
http://www.istool.net/

**Comment by JohnDMcMaster** [comment]
@diamondman I have an offer that someone might be able to attempt NSIS installer tonight. Should I give them a green light?

**Comment by diamondman** [comment]
Go ahead. I am happy to try it but do not delay on me.

**Comment by JohnDMcMaster** [comment]
Just got an update: "I have the installer mostly complete... I just need a Gimp or something to do the illustrations"

**Comment by d235j** [comment]
Could we use pyinstaller?

**Comment by JohnDMcMaster** [comment]
I've been given a NSIS based installer candidate. Going through some early testing now

**Comment by JohnDMcMaster** [comment]
I've added an official Windows release: https://github.com/AdamLaurie/rompar/releases

**Comment by JohnDMcMaster** [comment]
This is officially announced. I believe this is fixed at least in terms of installation. We may want to eliminate CLI usage, but I think that would be a separate ticket.
